/*
 * bitbanding.h
 *
 *  Created on: 19 θών. 2018 γ.
 *      Author: User
 */

#ifndef BITBANDING_H_
#define BITBANDING_H_

#define BITBAND_ADR_PERIPH(PERIPH_REG_ADR, BIT) (PERIPH_BB_BASE + (PERIPH_REG_ADR - PERIPH_BASE)*32 + BIT*4)

#define PortA_ODR(BIT) (*((volatile unsigned long *) BITBAND_ADR_PERIPH(GPIOA_BASE + 0x14, BIT)))
#define PortB_ODR(BIT) (*((volatile unsigned long *) BITBAND_ADR_PERIPH(GPIOB_BASE + 0x14, BIT)))
#define PortC_ODR(BIT) (*((volatile unsigned long *) BITBAND_ADR_PERIPH(GPIOC_BASE + 0x14, BIT)))
#define PortA_IDR(BIT) (*((volatile unsigned long *) BITBAND_ADR_PERIPH(GPIOA_BASE + 0x10, BIT)))
#define PortB_IDR(BIT) (*((volatile unsigned long *) BITBAND_ADR_PERIPH(GPIOB_BASE + 0x10, BIT)))
#define PortC_IDR(BIT) (*((volatile unsigned long *) BITBAND_ADR_PERIPH(GPIOC_BASE + 0x14, BIT)))

#define HIGH 1
#define LOW  0

#define PortA_pin_0 PortA_ODR(0)
#define PortA_pin_1 PortA_ODR(1)
#define PortA_pin_2 PortA_ODR(2)
#define PortA_pin_3 PortA_ODR(3)
#define PortA_pin_4 PortA_ODR(4)
#define PortA_pin_5 PortA_ODR(5)
#define PortA_pin_6 PortA_ODR(6)
#define PortA_pin_7 PortA_ODR(7)
#define PortA_pin_8 PortA_ODR(8)
#define PortA_pin_9 PortA_ODR(9)
#define PortA_pin_10 PortA_ODR(10)
#define PortA_pin_11 PortA_ODR(11)
#define PortA_pin_12 PortA_ODR(12)
#define PortA_pin_13 PortA_ODR(13)
#define PortA_pin_14 PortA_ODR(14)
#define PortA_pin_15 PortA_ODR(15)

#define PortA_inpin_0 PortA_IDR(0)
#define PortA_inpin_1 PortA_IDR(1)
#define PortA_inpin_2 PortA_IDR(2)
#define PortA_inpin_3 PortA_IDR(3)
#define PortA_inpin_4 PortA_IDR(4)
#define PortA_inpin_5 PortA_IDR(5)
#define PortA_inpin_6 PortA_IDR(6)
#define PortA_inpin_7 PortA_IDR(7)
#define PortA_inpin_8 PortA_IDR(8)
#define PortA_inpin_9 PortA_IDR(9)
#define PortA_inpin_10 PortA_IDR(10)
#define PortA_inpin_11 PortA_IDR(11)
#define PortA_inpin_12 PortA_IDR(12)
#define PortA_inpin_13 PortA_IDR(13)
#define PortA_inpin_14 PortA_IDR(14)
#define PortA_inpin_15 PortA_IDR(15)


#define PortB_pin_0 PortB_ODR(0)
#define PortB_pin_1 PortB_ODR(1)
#define PortB_pin_2 PortB_ODR(2)
#define PortB_pin_3 PortB_ODR(3)
#define PortB_pin_4 PortB_ODR(4)
#define PortB_pin_5 PortB_ODR(5)
#define PortB_pin_6 PortB_ODR(6)
#define PortB_pin_7 PortB_ODR(7)
#define PortB_pin_8 PortB_ODR(8)
#define PortB_pin_9 PortB_ODR(9)
#define PortB_pin_10 PortB_ODR(10)
#define PortB_pin_11 PortB_ODR(11)
#define PortB_pin_12 PortB_ODR(12)
#define PortB_pin_13 PortB_ODR(13)
#define PortB_pin_14 PortB_ODR(14)
#define PortB_pin_15 PortB_ODR(15)

#define PortB_inpin_0 PortB_IDR(0)
#define PortB_inpin_1 PortB_IDR(1)
#define PortB_inpin_2 PortB_IDR(2)
#define PortB_inpin_3 PortB_IDR(3)
#define PortB_inpin_4 PortB_IDR(4)
#define PortB_inpin_5 PortB_IDR(5)
#define PortB_inpin_6 PortB_IDR(6)
#define PortB_inpin_7 PortB_IDR(7)
#define PortB_inpin_8 PortB_IDR(8)
#define PortB_inpin_9 PortB_IDR(9)
#define PortB_inpin_10 PortB_IDR(10)
#define PortB_inpin_11 PortB_IDR(11)
#define PortB_inpin_12 PortB_IDR(12)
#define PortB_inpin_13 PortB_IDR(13)
#define PortB_inpin_14 PortB_IDR(14)
#define PortB_inpin_15 PortB_IDR(15)


#define PortC_pin_0 PortC_ODR(0)
#define PortC_pin_1 PortC_ODR(1)
#define PortC_pin_2 PortC_ODR(2)
#define PortC_pin_3 PortC_ODR(3)
#define PortC_pin_4 PortC_ODR(4)
#define PortC_pin_5 PortC_ODR(5)
#define PortC_pin_6 PortC_ODR(6)
#define PortC_pin_7 PortC_ODR(7)
#define PortC_pin_8 PortC_ODR(8)
#define PortC_pin_9 PortC_ODR(9)
#define PortC_pin_10 PortC_ODR(10)
#define PortC_pin_11 PortC_ODR(11)
#define PortC_pin_12 PortC_ODR(12)
#define PortC_pin_13 PortC_ODR(13)
#define PortC_pin_14 PortC_ODR(14)
#define PortC_pin_15 PortC_ODR(15)

#define PortC_inpin_0 PortC_IDR(0)
#define PortC_inpin_1 PortC_IDR(1)
#define PortC_inpin_2 PortC_IDR(2)
#define PortC_inpin_3 PortC_IDR(3)
#define PortC_inpin_4 PortC_IDR(4)
#define PortC_inpin_5 PortC_IDR(5)
#define PortC_inpin_6 PortC_IDR(6)
#define PortC_inpin_7 PortC_IDR(7)
#define PortC_inpin_8 PortC_IDR(8)
#define PortC_inpin_9 PortC_IDR(9)
#define PortC_inpin_10 PortC_IDR(10)
#define PortC_inpin_11 PortC_IDR(11)
#define PortC_inpin_12 PortC_IDR(12)
#define PortC_inpin_13 PortC_IDR(13)
#define PortC_inpin_14 PortC_IDR(14)
#define PortC_inpin_15 PortC_IDR(15)

#define PortD_pin_0 PortD_ODR(0)
#define PortD_pin_1 PortD_ODR(1)
#define PortD_pin_2 PortD_ODR(2)
#define PortD_pin_3 PortD_ODR(3)
#define PortD_pin_4 PortD_ODR(4)
#define PortD_pin_5 PortD_ODR(5)
#define PortD_pin_6 PortD_ODR(6)
#define PortD_pin_7 PortD_ODR(7)
#define PortD_pin_8 PortD_ODR(8)
#define PortD_pin_9 PortD_ODR(9)
#define PortD_pin_10 PortD_ODR(10)
#define PortD_pin_11 PortD_ODR(11)
#define PortD_pin_12 PortD_ODR(12)
#define PortD_pin_13 PortD_ODR(13)
#define PortD_pin_14 PortD_ODR(14)
#define PortD_pin_15 PortD_ODR(15)

#define PortD_inpin_0 PortD_IDR(0)
#define PortD_inpin_1 PortD_IDR(1)
#define PortD_inpin_2 PortD_IDR(2)
#define PortD_inpin_3 PortD_IDR(3)
#define PortD_inpin_4 PortD_IDR(4)
#define PortD_inpin_5 PortD_IDR(5)
#define PortD_inpin_6 PortD_IDR(6)
#define PortD_inpin_7 PortD_IDR(7)
#define PortD_inpin_8 PortD_IDR(8)
#define PortD_inpin_9 PortD_IDR(9)
#define PortD_inpin_10 PortD_IDR(10)
#define PortD_inpin_11 PortD_IDR(11)
#define PortD_inpin_12 PortD_IDR(12)
#define PortD_inpin_13 PortD_IDR(13)
#define PortD_inpin_14 PortD_IDR(14)
#define PortD_inpin_15 PortD_IDR(15)


#endif /* BITBANDING_H_ */
